/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.mysampleproject.db;

import android.content.Context;
import com.example.mysampleproject.db.AbstractSampleDBOpenHelper;


public class SampleDBOpenHelper extends AbstractSampleDBOpenHelper {
	public SampleDBOpenHelper(Context context) {
		super(context);
	}
}
