/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.operationexecutor;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import android.content.Intent;
import android.os.Bundle;

public abstract class AbstractSetupOperation extends Operation {
	public static final String ACTION_SETUP = "com.example.operationexecutor.MovieService.actions.SETUP";


	static class Args {
	}
	
	static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new SetupOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {
			Intent existingRequest = bridge.findPendingRequestByActionWithExtras(AbstractSetupOperation.ACTION_SETUP, intent.getExtras());
			
			return existingRequest;
			
		}
	}
	
	public static final Intent newIntent() {
		Intent intent = new Intent(ACTION_SETUP);
		intent.setClass(Mechanoid.getApplicationContext(), MovieService.class);
		
		Bundle extras = new Bundle();
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute() {
		Args args = new Args();
		
		return onExecute(args);
	}
			
	protected abstract OperationResult onExecute(Args args);
}
