/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.operationexecutor;

import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;
import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;

public abstract class AbstractMovieServiceConfiguration extends OperationServiceConfiguration {
	private OperationConfigurationRegistry mOperationConfigurationRegistry = new MovieServiceOperationConfigurationRegistry();
	
	@Override
	public OperationConfigurationRegistry getOperationConfigurationRegistry() {
		return mOperationConfigurationRegistry;
	}
}
