/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.operationexecutor;

import java.util.HashMap;

import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;
import com.robotoworks.mechanoid.ops.OperationConfiguration;

public abstract class AbstractMovieServiceOperationConfigurationRegistry extends OperationConfigurationRegistry {
	
	private HashMap<String, OperationConfiguration> mOperationConfigurations;
	
	public AbstractMovieServiceOperationConfigurationRegistry() {
		
		mOperationConfigurations = new HashMap<String, OperationConfiguration>();
		
		registerOperationConfigurations();
	}
	
	protected void registerOperationConfigurations(){
		registerOperationConfiguration(SetupOperation.ACTION_SETUP, new SetupOperation.Configuration());
	}
	
	protected void registerOperationConfiguration(String action, OperationConfiguration config) {
		mOperationConfigurations.put(action, config);
	}

	@Override
	public OperationConfiguration getOperationConfiguration(String action) {
		return mOperationConfigurations.get(action);
	}
}
