/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.operationexecutor;

import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationProcessor;			

public abstract class AbstractMovieProcessor extends OperationProcessor {

	@Override
	protected Operation createOperation(String action) {
		return MovieService.CONFIG
			.getOperationConfigurationRegistry()
			.getOperationConfiguration(action)
			.createOperation();
	}
	
	public AbstractMovieProcessor(OperationService service, boolean enableLogging) {
		super(service, enableLogging);
	}
}
