/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.operationexecutor;

import com.example.operationexecutor.AbstractMovieService;

public class MovieService extends AbstractMovieService {
	public MovieService() {
		super(false);
	}
}
