/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.operationexecutor;

import com.robotoworks.mechanoid.ops.OperationService;

public class MovieProcessor extends AbstractMovieProcessor {
	public MovieProcessor(OperationService service) {
		super(service, false);
	}
}
