/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.operationexecutor;

public class MovieServiceOperationConfigurationRegistry extends AbstractMovieServiceOperationConfigurationRegistry {
	
}

