/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.operationexecutor;

import com.robotoworks.mechanoid.ops.OperationResult;

public class SetupOperation extends AbstractSetupOperation {
	@Override
	protected OperationResult onExecute(Args args) {
		return OperationResult.ok();
	}
}
