/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.mysampleproject.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.MechanoidSQLiteOpenHelper;
import com.robotoworks.mechanoid.db.SQLiteMigration;


public abstract class AbstractSampleDBOpenHelper extends MechanoidSQLiteOpenHelper {
	private static final String DATABASE_NAME = "SampleDB.db";

	public static final int VERSION = 1;

	public interface Sources {
		String ARTISTS = "artists";
		String ARTISTS_VIEW = "artists_view";
	}

	public AbstractSampleDBOpenHelper(Context context) {
		super(context, DATABASE_NAME, null, VERSION);
	}

	public AbstractSampleDBOpenHelper(Context context, String name) {
		super(context, name, null, VERSION);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		db.execSQL(
			"create table artists ( " +
			"_id integer primary key autoincrement, " +
			"name text " +
			") "
		);	
		db.execSQL(
			"create view artists_view as " +
			"select " +
			"a._id as _id, " +
			"a.name as name " +
			"from artists as a "
		);	
	}

	@Override
	protected SQLiteMigration createMigration(int version) {
		throw new IllegalStateException("No migrations for any version");
	}
	
}
