/*
 * Generated by Robotoworks Mechanoid
 */
package com.example.mysampleproject.db;

import android.net.Uri;
import android.provider.BaseColumns;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;
import java.lang.reflect.Field;

public class SampleDBContract  {
    public static final String CONTENT_AUTHORITY = initAuthority();

	private static String initAuthority() {
		String authority = "com.example.mysampleproject.db.sampledb";

		try {
    		
    		ClassLoader loader = SampleDBContract.class.getClassLoader();
    		
			Class<?> clz = loader.loadClass("com.example.mysampleproject.db.SampleDBContentProviderAuthority");
			Field declaredField = clz.getDeclaredField("CONTENT_AUTHORITY");
			
			authority = declaredField.get(null).toString();
		} catch (ClassNotFoundException e) {} 
    	catch (NoSuchFieldException e) {} 
    	catch (IllegalArgumentException e) {
		} catch (IllegalAccessException e) {
		}
		
		return authority;
	}
	
    private static final Uri BASE_CONTENT_URI = Uri.parse("content://" + CONTENT_AUTHORITY);

	interface ArtistsColumns {
		String NAME = "name";
	}
	

	interface ArtistsViewColumns {
		String NAME = "name";
	}
	
			
	/**
	 * <p>Column definitions and helper methods to work with the Artists.</p>
	 */
	public static class Artists implements ArtistsColumns, BaseColumns {
	    public static final Uri CONTENT_URI = 
				BASE_CONTENT_URI.buildUpon().appendPath("artists").build();
	
		/**
		 * <p>The content type for a cursor that contains many Artists rows.</p>
		 */
	    public static final String CONTENT_TYPE =
	            "vnd.android.cursor.dir/vnd.sampledb.artists";
	
		/**
		 * <p>The content type for a cursor that contains a single Artists row.</p>
		 */
		public static final String ITEM_CONTENT_TYPE =
			"vnd.android.cursor.item/vnd.sampledb.artists";
	
		/**
		 * <p>Builds a Uri with appended id for a row in Artists, 
		 * eg:- content://com.example.mysampleproject.db.sampledb/artists/123.</p>
		 */
	    public static Uri buildUriWithId(long id) {
	        return CONTENT_URI.buildUpon().appendPath(String.valueOf(id)).build();
	    }
		public static int delete() {
			return Mechanoid.getContentResolver().delete(CONTENT_URI, null, null);
		}
		
		public static int delete(String where, String[] selectionArgs) {
			return Mechanoid.getContentResolver().delete(CONTENT_URI, where, selectionArgs);
		}
		
		/**
		 * <p>Create a new Builder for Artists</p>
		 */
		public static Builder newBuilder() {
			return new Builder();
		}
		
		/**
		 * <p>Build and execute insert or update statements for Artists.</p>
		 *
		 * <p>Use {@link Artists#newBuilder()} to create new builder</p>
		 */
		public static class Builder extends AbstractValuesBuilder {
			private Builder() {
				super(Mechanoid.getApplicationContext(), CONTENT_URI);
			}
			
			public Builder setName(String value) {
				mValues.put(Artists.NAME, value);
				return this;
			}
		}
	}

	/**
	 * <p>Column definitions and helper methods to work with the ArtistsView.</p>
	 */
	public static class ArtistsView implements ArtistsViewColumns, BaseColumns {
	    public static final Uri CONTENT_URI = 
				BASE_CONTENT_URI.buildUpon().appendPath("artists_view").build();
	
		/**
		 * <p>The content type for a cursor that contains many ArtistsView rows.</p>
		 */
	    public static final String CONTENT_TYPE =
	            "vnd.android.cursor.dir/vnd.sampledb.artists_view";
	
		/**
		 * <p>The content type for a cursor that contains a single ArtistsView row.</p>
		 */
		public static final String ITEM_CONTENT_TYPE =
			"vnd.android.cursor.item/vnd.sampledb.artists_view";
	
		/**
		 * <p>Builds a Uri with appended id for a row in ArtistsView, 
		 * eg:- content://com.example.mysampleproject.db.sampledb/artists_view/123.</p>
		 */
	    public static Uri buildUriWithId(long id) {
	        return CONTENT_URI.buildUpon().appendPath(String.valueOf(id)).build();
	    }
		public static int delete() {
			return Mechanoid.getContentResolver().delete(CONTENT_URI, null, null);
		}
		
		public static int delete(String where, String[] selectionArgs) {
			return Mechanoid.getContentResolver().delete(CONTENT_URI, where, selectionArgs);
		}
		
		/**
		 * <p>Create a new Builder for ArtistsView</p>
		 */
		public static Builder newBuilder() {
			return new Builder();
		}
		
		/**
		 * <p>Build and execute insert or update statements for ArtistsView.</p>
		 *
		 * <p>Use {@link ArtistsView#newBuilder()} to create new builder</p>
		 */
		public static class Builder extends AbstractValuesBuilder {
			private Builder() {
				super(Mechanoid.getApplicationContext(), CONTENT_URI);
			}
			
			public Builder setName(String value) {
				mValues.put(ArtistsView.NAME, value);
				return this;
			}
		}
	}
	
	private SampleDBContract(){}
}
